### ISSUE TITLE
Bad installation guide.

### ISSUE THREAD

**Issue by Pawat-Sarnchawanakit** [opxz7148/ku-polls#87]
There is no mention of running requirements of any kind such as what Python version is needed or whether Git is needed.  

`Change directories to work directories` is confusing and doesn't make any sense. Did you mean "Change current working directory"?

There is no instruction on how to download the app.  
This might be why, the first command `cd ku-polls` does not work.  
It said `cd: ku-polls: No such file or directory`  

The "activate virtual enviroments" <- notice how `environment` is misspelled, missing an `n` as well as having an `s` at the back for some reason.  
The instruction does not work in Linux.
![image](https://github.com/user-attachments/assets/124b6992-db57-447c-942a-9550dfe15db9)  
This might be because of how the instruction said to create the virtual environment named `.venv` while also saying to activate a virtual environment named `env`.

**Comment by opxz7148** [comment]
Updated In #92
