### ISSUE TITLE
Poll boxes overlapping each other in polls page on small width screen.

### ISSUE THREAD

**Issue by Pawat-Sarnchawanakit** [opxz7148/ku-polls#89]
This makes the title and dates unreadable.  
This issue persists even after a refresh.  
Expected the boxes to wrapped around and be able to scroll down to view the rest of the polls.  
  
![image](https://github.com/user-attachments/assets/b57841a1-f69a-4fcf-bdf6-a38b96d3b8a0)

**Comment by opxz7148** [comment]
Can I know which browser you're using?

**Comment by Pawat-Sarnchawanakit** [comment]
Firefox 130.0

**Comment by opxz7148** [comment]
This is consequence from #90 so it already got fixed in #92
