### ISSUE TITLE
WARNING Not Found: `/static/polls/style.css` spammed in logs

### ISSUE THREAD

**Issue by Pawat-Sarnchawanakit** [opxz7148/ku-polls#90]
This warning message keeps showing up in logs every time I use KU Polls.  
  
![image](https://github.com/user-attachments/assets/1d839102-8487-4a6d-becd-f1c9e9ac0040)

**Comment by opxz7148** [comment]
This cause by DEBUG=False. I've fix it's in #92 to make css file available when DEBUG=False.
