### ISSUE TITLE
Example polls, poll title only one ends with a question mark.

### ISSUE THREAD

**Issue by Pawat-Sarnchawanakit** [opxz7148/ku-polls#91]
**This is just a suggestion**  

In the example polls given in the data fixture, I have noticed something weird.  
Despite all the polls' title being questions, only one of them ends which a question mark.  
Also that poll title is the only one that is the contraction `What is` -> `What's`  
Can you make the example polls a bit more consistent?  

![image](https://github.com/user-attachments/assets/342172f4-96b7-4878-9f79-fa4b590841d5)

**Comment by opxz7148** [comment]
Fixed in #92
